version: '3.8'
name: app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    expose:
      - 3000
    networks:
      - traefik
      - default
    volumes:
      - media:/app/dist/media
    environment:
      NODE_ENV: production
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=(Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`))
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=letsencrypt
      - traefik.http.routers.app.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.app.tls.domains[0].sans=www.${DOMAIN}
      - traefik.http.routers.app.middlewares=to-nonwww
      - traefik.docker.network=traefik
    restart: always
  
networks:
  traefik:
    external: true

volumes:
  media:
    name: media
  data: