version: '3.8'

services:
  app:
    image: node:18-alpine
    ports:
      - 3000:3000
      - 8002:8002 # remix dev websocket for live reload
    working_dir: /app
    command: sh -c "yarn && yarn dev"
    volumes:
      - ./:/app
      - /app/node_modules
  
volumes:
  data: